version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MYSQL_PASSWORD=your_password
      - MYSQL_DATABASE=ecommerce
      - MYSQL_HOST=db
    links:
      - db

volumes:
  db_data: